sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t arikarniawan/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true arikarniawan/react-test npm test -- --coverage

after_succes:
    - docker build -t arikarniawan/multi-client ./client
    - docker build -t arikarniawan/multi-nginx ./nginx
    - docker build -t arikarniawan/multi-server ./server
    - docker build -t arikarniawan/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push arikarniawan/multi-client
    - docker push arikarniawan/multi-nginx
    - docker push arikarniawan/multi-server
    - docker push arikarniawan/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: 'ap-southeast-1'
    app: 'multi-docker'
    env: 'MultiDocker-env'
    bucket_name: 'elasticbeanstalk-ap-southeast-1-889862894947'
    bucket_path: 'docker-multi'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    