sudo: required
services:
    - docker

before_install:
    - docker build -t arikarniawan/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true arikarniawan/react-test npm test

after_succes:
    - docker build -t arikarniawan/multi-client ./client
    - docker build -t arikarniawan/multi-nginx ./nginx
    - docker build -t arikarniawan/multi=server ./server
    - docker build -t arikarniawan/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push arikarniawan/multi-client
    - docker push arikarniawan/multi-nginx
    - docker push arikarniawan/multi-server
    - docker push arikarniawan/multi-worker
